version: '3.7'
services:
    postgres:
        image: postgres:15.2-alpine3.17
        restart: always
        environment:
          POSTGRES_USER: beva
          POSTGRES_PASSWORD: beva@2023
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data:rw